# Generated by Django 5.2.11 on 2026-02-24 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_ssh_keys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshkey',
            name='comment',
        ),
    ]
