# Generated by Django 5.2.11 on 2026-02-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_ssh_keys', '0002_remove_sshkey_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SSHKeyAssignment',
        ),
    ]
