# Generated by Django 5.2 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netbox_ssh_keys', '0003_delete_sshkeyassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sshkey',
            name='public_key',
            field=models.CharField(
                help_text='Base64-encoded public key material (without type prefix or comment)',
                max_length=1023,
            ),
        ),
    ]
